# Generated by Django 2.2.2 on 2019-11-27 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='Valid_to',
            new_name='valid_to',
        ),
    ]
