# Generated by Django 2.2.2 on 2019-11-26 13:50

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('paystack', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymenthistory',
            name='data',
            field=jsonfield.fields.JSONField(),
        ),
    ]
